/* Authentication */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";

export const GET_YOUTUBES = "GET_YOUTUBES";
export const GET_YOUTUBES_SUCCESS = "GET_YOUTUBES_SUCCESS";
export const GET_YOUTUBES_FAIL = "GET_YOUTUBES_FAIL";

export const GET_MESSAGE = "GET_MESSAGE";
export const GET_CONNECTION_COUNT = "GET_CONNECTION_COUNT";
export const GET_ROOM_USERLIST = "GET_ROOM_USERLIST";
export const UPDATE_CURRENT_ROOM = "UPDATE_CURRENT_ROOM";
export const CONNECTION_ADD = "CONNECTION_ADD";
export const CONNECTION_DELETE = "CONNECTION_DELETE";
export const LEAVE_ROOM = "LEAVE_ROOM";